# Generated by Django 6.0.4 on 2026-04-29 05:13

from django.db import migrations


def migrate_images(apps, schema_editor):
    cars = apps.get_model('login', 'cars')
    CarImage = apps.get_model('login', 'CarImage')
    for car in cars.objects.exclude(image='').exclude(image=None):
        if not CarImage.objects.filter(car=car).exists():
            CarImage.objects.create(car=car, image=car.image, is_main=True)


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_carimage'),
    ]

    operations = [
        migrations.RunPython(migrate_images, migrations.RunPython.noop),
    ]
